test: verified_contracts match related constraints
verifier-alliance/database-specs pull request #17
Opened 2024-09-16 13:05 UTC by rimrakhimov

- Add tests for verified_contracts constraints related to matches integrity
- Fix failing creation_values and runtime_values constraints when `NULL` value is inserted

2024-09-17 13:12 UTC, kuzdogan requested changes
We could do one addition. Otherwise lgtm

2024-09-17 13:12 UTC, kuzdogan commented on tests/test_table_verified_contracts.py
> +    @pytest.mark.parametrize("field,value", [("creation_values", dict()), ("creation_transformations", []), ("creation_metadata_match", False)])
Should we test for the inverse case of this too? Here the `creation_match` is `False` but one of the fields have a a positive value:
```js
// ("creation_values", dict())
{
  creation_match: False,
  creation_values: dict(), <-- unexpected
  creation_transformations: Null,
  creation_metadata_match: Null
}
```

but the inverse would test for when the `creation_match` is `True` and there's a `NULL`:
```js
// ("creation_values", Null)
{
  creation_match: True,
  creation_values: Null, <-- unexpected
  creation_transformations: [],
  creation_metadata_match: True
}
```

Same for `runtime_match`

2024-09-18 11:38 UTC, rimrakhimov commented on tests/test_table_verified_contracts.py
> +    @pytest.mark.parametrize("field,value", [("creation_values", dict()), ("creation_transformations", []), ("creation_metadata_match", False)])
Those tests already existed as `test_creation_match_without_details_fails` and `test_runtime_match_without_details_fails` but I've additionally added their explicit initialization in https://github.com/verifier-alliance/database-specs/pull/17/commits/5409b90de889a5b78fa6c724cc97b8087b3b2753

2024-09-18 11:46 UTC, kuzdogan commented on tests/test_table_verified_contracts.py
> +    @pytest.mark.parametrize("field,value", [("creation_values", dict()), ("creation_transformations", []), ("creation_metadata_match", False)])
Yeah my bad, thanks though

2024-09-18 11:56 UTC, merged